name: General Tests
on: [push, pull_request]
jobs:
  generaltests:
    strategy:
      matrix:
        distro:
          [
            "Alpine",
            "Debian",
            "kali-linux",
            "openSUSE-Leap-15.2",
            "Ubuntu-20.04",
            "Ubuntu-18.04",
          ]
    name: General Tests
    runs-on: windows-2019
    defaults:
      run:
        # The default shell is changed to a WSL
        shell: wsl-bash {0}
    steps:
      - uses: actions/checkout@v2
        name: Git Clone
      - uses: Vampire/setup-wsl@v1
        with:
          distribution: ${{ matrix.distro }}
          additional-packages:
            bash
            sudo 
            bc
            gzip
            make
            bash-completion
            imagemagick
            bats
        name: Install WSL Distro
        # TODO: Enable make test after test module is fixed.
      - run: bats -r tests
        name: Execute tests
