name: General Tests
on: [pull_request]
jobs:
  generaltests:
    strategy:
      matrix:
        distro:
          [
            "Alpine",
            "Debian",
            "kali-linux",
            "openSUSE-Leap-15.2",
            "Ubuntu-20.04",
            "Ubuntu-18.04",
          ]
    name: General Tests
    runs-on: windows-2019
    defaults:
      run:
        shell: wsl-bash {0}
    steps:
      - uses: actions/checkout@v2
        name: Git Clone
      - uses: Vampire/setup-wsl@v1
        with:
          distribution: ${{ matrix.distro }}
          additional-packages: 
            bc
            gzip
            make
            imagemagick
            bats
        name: Configure WSL Distro
      - run: ./configure.sh
        name: Configure Environment
        # TODO: Enable make test after test module is fixed.
      - run: bats -r tests
        name: Execute tests
